from unittest.mock import patch
from backend.model_client import JsonGenerationResult, get_active_provider_info, extract_code, extract_json
from backend.sandbox import parse_unittest_telemetry
from backend.workflow import run_workflow


def test_fibonacci_loop_fixes_the_seeded_bug():
    buggy_fib_code = '''"""Fibonacci utilities generated by BobBuilder."""

def fibonacci(n: int) -> int:
    if not isinstance(n, int) or isinstance(n, bool):
        raise TypeError("n must be an integer")
    if n < 0:
        raise ValueError("n must be non-negative")
    if n <= 1:
        return 1
    previous, current = 0, 1
    for _ in range(2, n + 1):
        previous, current = current, previous + current
    return current
'''
    fib_tests = '''import unittest
from main import fibonacci

class FibonacciContractTests(unittest.TestCase):
    def test_sequence_start(self):
        self.assertEqual(fibonacci(0), 0)
        self.assertEqual(fibonacci(1), 1)
'''
    fixed_fib_code = '''"""Fibonacci utilities generated by BobBuilder."""

def fibonacci(n: int) -> int:
    """Return the nth Fibonacci number for a non-negative index."""
    if not isinstance(n, int) or isinstance(n, bool):
        raise TypeError("n must be an integer")
    if n < 0:
        raise ValueError("n must be non-negative")
    if n <= 1:
        return n
    previous, current = 0, 1
    for _ in range(2, n + 1):
        previous, current = current, previous + current
    return current


if __name__ == "__main__":
    print(fibonacci(10))
'''
    mock_llm_res = JsonGenerationResult(
        data={
            "code": fixed_fib_code,
            "passed": True,
            "summary": "Fibonacci implementation satisfies contract.",
            "findings": [],
            "rationale": "Repaired base case to return n for n <= 1.",
        },
        provider="anthropic",
        status="success",
        source="anthropic",
    )

    with patch("backend.agents.CLIENT.generate_json", return_value=mock_llm_res), \
         patch("backend.agents._local_program", return_value=("fibonacci", buggy_fib_code, fib_tests)):
        result = run_workflow(
            "Build a Python function that returns the nth Fibonacci number. Handle n=0 and n=1, reject negative values, validate types, and include a CLI.",
            max_iterations=3,
            run_tests=True,
        )
    assert result["test_result"]["passed"] is True
    assert result["iterations"] == 1
    assert "return n" in result["code"]
    assert result["events"][-1]["phase"] == "complete"


def test_fixer_provider_error_halts_and_does_not_inflate_patches():
    from backend.model_client import ProviderError, GenerationResult
    buggy_code = "def solve(): return False\n"
    failing_tests = """import unittest
from main import solve
class Tests(unittest.TestCase):
    def test_it(self):
        self.assertTrue(solve())
"""
    provider_err_res = JsonGenerationResult(
        data=None,
        provider="anthropic",
        status="provider_error",
        source="anthropic",
        error=ProviderError(provider="anthropic", message="Anthropic quota error: Credit balance is too low", category="quota_exceeded"),
    )
    raw_provider_err = GenerationResult(
        text="",
        provider="anthropic",
        status="provider_error",
        source="anthropic",
        error=ProviderError(provider="anthropic", message="Anthropic quota error: Credit balance is too low", category="quota_exceeded"),
    )
    with patch("backend.agents.CLIENT.generate_json", return_value=provider_err_res), \
         patch("backend.agents.CLIENT.generate", return_value=raw_provider_err), \
         patch("backend.agents._local_program", return_value=("generic", buggy_code, failing_tests)):
        result = run_workflow("Implement a solver function", max_iterations=3)

    assert result["test_result"]["passed"] is False
    # Stopped at iteration 1 instead of continuing to 3
    assert result["iterations"] == 1
    assert result["repair_blocked"] is True
    assert "Repair stopped:" in result["message"]
    # Check that events do not claim "Applied patch"
    fixer_events = [e for e in result["events"] if e["agent"] == "Fixer"]
    assert len(fixer_events) == 1
    assert "Repair attempt 1 failed:" in fixer_events[0]["message"]
    assert "Applied patch" not in fixer_events[0]["message"]
    # History contains ONLY Builder draft, no fake patch iterations
    assert len(result["history"]) == 1
    assert result["history"][0]["agent"] == "Builder"


def test_prime_template_is_clean_on_first_pass():
    result = run_workflow("Build a Python utility that checks whether an integer is prime.", max_iterations=2)
    assert result["test_result"]["passed"] is True
    assert result["iterations"] == 0


def test_lru_cache_workflow():
    result = run_workflow("Implement a Least Recently Used (LRU) Cache with capacity eviction and O(1) lookups.")
    assert result["test_result"]["passed"] is True
    assert result["challenge"] == "lru_cache"
    assert "class LRUCache" in result["code"]
    assert result["test_result"]["passed_count"] >= 3


def test_rate_limiter_workflow():
    result = run_workflow("Build a Token Bucket Rate Limiter with refill rate and request capacity limits.")
    assert result["test_result"]["passed"] is True
    assert result["challenge"] == "rate_limiter"
    assert "class RateLimiter" in result["code"]


def test_binary_search_workflow():
    result = run_workflow("Implement a binary search algorithm for sorted lists returning the target index or -1.")
    assert result["test_result"]["passed"] is True
    assert result["challenge"] == "binary_search"
    assert "def binary_search" in result["code"]


def test_dijkstra_workflow():
    result = run_workflow("Build Dijkstra's shortest path algorithm for weighted directed graphs.")
    assert result["test_result"]["passed"] is True
    assert result["challenge"] == "dijkstra"
    assert "def dijkstra" in result["code"]


def test_email_validator_workflow():
    result = run_workflow("Build an RFC-standard email validator with regex syntax checks.")
    assert result["test_result"]["passed"] is True
    assert result["challenge"] == "email_validator"
    assert "def validate_email" in result["code"]


def test_arbitrary_prompt_workflow():
    result = run_workflow("Write a function to calculate exponentiation of a matrix or general numbers.")
    assert result["test_result"]["passed"] is True
    assert len(result["code"]) > 0
    assert len(result["tests"]) > 0


def test_model_client_provider_info():
    info = get_active_provider_info()
    assert "mode" in info
    assert "active" in info
    assert isinstance(info["configured_providers"], list)


def test_sandbox_telemetry_extraction():
    sample_stderr = """test_one (test_main.Tests.test_one) ... FAIL
test_two (test_main.Tests.test_two) ... ok

======================================================================
FAIL: test_one (test_main.Tests.test_one)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_main.py", line 4, in test_one
    self.assertEqual(1, 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
"""
    telemetry = parse_unittest_telemetry("", sample_stderr)
    assert telemetry["total_count"] == 2
    assert telemetry["passed_count"] == 1
    assert telemetry["failing_tests"] == ["test_one"]
    assert "AssertionError: 1 != 2" in telemetry["assertion_error"]


def test_model_client_extraction_helpers():
    code_snippet = "```python\ndef hello(): pass\n```"
    assert extract_code(code_snippet) == "def hello(): pass"

    json_snippet = '```json\n{"status": "ok", "count": 42}\n```'
    assert extract_json(json_snippet) == {"status": "ok", "count": 42}


def test_workflow_java_selection():
    result = run_workflow("Given an array of integers nums and an integer target, return indices of two numbers that add up to target.", language="java")
    assert result["language"] == "java"
    assert "class Solution" in result["code"]
    assert "public int[] twoSum" in result["code"]
    assert "def " not in result["code"]
    assert result["test_result"]["passed"] is True


def test_workflow_cpp_selection():
    result = run_workflow("Given an array of integers nums and an integer target, return indices of two numbers that add up to target.", language="cpp")
    assert result["language"] == "cpp"
    assert "class Solution" in result["code"]
    assert "vector<int>" in result["code"]
    assert "def " not in result["code"]
    assert result["test_result"]["passed"] is True



